### ISSUE TITLE
Discussion 🥇 

### ISSUE THREAD

**Issue by flowck** [arthureichelberger/goboiler#3]
Hey @arthureichelberger, I came across your repo from Twitter, and I personally liked how clear its structure is. More than anything I would like to get your perspective on a few questions I've written down below.

### Env variable default values

I understand the convenience of providing default values to env variables but it seems to me that it could potentially make debugging harder if one of those variables were not set when deployed to a cloud provider. I reckon that the service would just attempt to initialise itself with the default values. What is your take on this topic? Has it ever happened to you?

```go
db, err := psql.Connect(
      ctx,
      env("DATABASE_USERNAME", "postgres"),
      env("DATABASE_PASSWORD", "postgres"),
      env("DATABASE_HOST", "localhost"),
      env("DATABASE_PORT", "5432"),
      env("DATABASE_NAME", "postgres"),
)
```

### HTTP server's context

The server can optionally take a base context, which can increase one's control during the cancellation of the main context. 
_Ref: https://www.digitalocean.com/community/tutorials/how-to-make-an-http-server-in-go_

```go
//...
httpServer := &http.Server{
      // ... 
      BaseContext: func(listener net.Listener) context.Context {
            return ctx
      },
}
//...
```

### HTTP handlers as methods of a struct

```go
router.GET("/dummy", handler.DummyHandler(dummyService))
```

What's your take on defining the http handlers as methods of a struct? The current implementation on this repo uses a closure to inject the service to the handlers, which works very well, however it made me think about the possibility of having the handlers defined as methods of a struct that would hold the service/services or any other dependency as fields which can later be accessed from the method/handler:

```go
type Handlers struct {
	dummyService *service.DummyService
}

func (h *Handlers) DummyHandler(c *gin.Context) {
	ctx := c.Request.Context()

	count, err := h.dummyService.Dummy(ctx)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, gin.H{"count": count})
}
```
And then registered like this:

```go
// assuming that there is constructor for the struct
handlers := NewHandlers(dummyService)


router.GET("/dummy", handler.DummyHandler(dummyService))
```

### OpenAPI code generation?

What's your take on tools such as https://github.com/deepmap/oapi-codegen? [Demo with Gin](https://github.com/deepmap/oapi-codegen/tree/master/examples/petstore-expanded/gin)

Thanks for your openness and I hope this doesn't come across as off putting.

Cheers,
Firmino

**Comment by arthureichelberger** [comment]
Hey @flowck! 👋

Thanks a lot for taking the time to review this and for your feedbacks. 🙏

> I understand the convenience of providing default values to env variables but it seems to me that it could potentially make debugging harder if one of those variables were not set when deployed to a cloud provider. I reckon that the service would just attempt to initialise itself with the default values. What is your take on this topic? Has it ever happened to you?

I have experienced this issue a few times but mostly on our "build" _(call it whatever you want, QA, dev, preprod, staging...)_ environment so without any impact on end customers. I am mostly deploying to cloud providers with Kubernetes, using Helm Charts so once I put one value in build, I make sure to put it as well for production. I reckon this is something we could/should act on by either returning an error or by panicking directly in the `env` function but given how convenient this is to run the server locally, I would still keep it as is.

> The server can optionally take a base context, which can increase one's control during the cancellation of the main context.

That is something I'm discovering right now, I'll be exploring that option and will come back to you later!

> What's your take on defining the http handlers as methods of a struct? The current implementation on this repo uses a closure to inject the service to the handlers, which works very well, however it made me think about the possibility of having the handlers defined as methods of a struct that would hold the service/services or any other dependency as fields which can later be accessed from the method/handler:

I used to work with "controllers" that were struct, responsible for a list of endpoints _(e.g. UserController responsible for all user operations..)_. I switched to this closure approach because it feels more "flexible" but I guess both approach can be effective solutions.

> What's your take on tools such as https://github.com/deepmap/oapi-codegen? [Demo with Gin](https://github.com/deepmap/oapi-codegen/tree/master/examples/petstore-expanded/gin)

I don't have a lot of arguments against but weirdly, I don't really like this approach. I have worked with such tools outside of the Golang ecosystem and had some weird results (mainly with PHP) so I should give it another try to have a refreshed opinion on the topic.

Once again, thanks a lot for your feedback and for this discussion! 🙏

**Comment by arthureichelberger** [comment]
About contexts; I did a few tests and it seems that it does not stop the server while cancelling the context. Reading the documentation, I understand that it pass the context to the requests and I do not think that it's a good idea if we think about graceful shutdown.

By doing this, it would mean that when a signal is trapped, we will cancel all requests meaning that all requests may fail. My approach is rather to give a bit of time to the server (not done yet, but a good improvement) to stop itself and to finish all work in progress. This, coupled with Kubernetes probes (not done yet as well) will basically creates the following workflow:
- A stop signal is trapped.
- The pod no longer accept incoming requests (that's the role of the probes).
- But the pod still have time to properly stop and to finish ongoing requests (this time needs to be configurable because depending on your use cases, you may need 2 seconds, 10 seconds.. default Kubernetes grace time is 30 seconds so anything below that is "ok").
- When everything is settled, pod shutdowns.

I'll run some other tests to be sure that my understanding is right but I do believe this is one good "conservative" approach.

**Comment by flowck** [comment]
>  I reckon this is something we could/should act on by either returning an error or by panicking directly in the env function but given how convenient this is to run the server locally, I would still keep it as is.

I've been bitten a few times by missing env variables, so nowadays I quite like a more pessimistic behaviour just to catch the issue as early as possible. =D

> I don't have a lot of arguments against but weirdly, I don't really like this approach. I have worked with such tools outside of the Golang ecosystem and had some weird results (mainly with PHP) so I should give it another try to have a refreshed opinion on the topic.

Personally these are the reasons that leads me towards using oapi-codegen:

- Writing a spec as I write build the API
- Being able to generate an API client, which comes in handy when testing the API itself, or when exposing the API to other services. At my job we perform inter-service communication using HTTP, so code generation saves us a lot of work.
- Types, types and types. Having it generated for me is a time-saver.

**Comment by arthureichelberger** [comment]
> I've been bitten a few times by missing env variables, so nowadays I quite like a more pessimistic behaviour just to catch the issue as early as possible. =D

I had the discussion on the Golang Insiders community on X and one great thing came out: adding a warning or a debug log when te default value is used! 🙌 

> Personally these are the reasons that leads me towards using oapi-codegen:
Writing a spec as I write build the API
Being able to generate an API client, which comes in handy when testing the API itself, or when exposing the API to other services. At my job we perform inter-service communication using HTTP, so code generation saves us a lot of work.
Types, types and types. Having it generated for me is a time-saver.

I will definitely give it a look then! You should also check out gRPC for inter-service communication! 💪

**Comment by arthureichelberger** [comment]
I am closing this as we covered all points, agree @flowck?

**Comment by flowck** [comment]
> I will definitely give it a look then! You should also check out gRPC for inter-service communication! 💪

For now we are stuck with Heroku which makes it harder to expose multiple ports per service. :(

> I am closing this as we covered all points, agree @flowck?

Agreed, it was very pleasant to re-explore some of the topics we discussed.

Cheers,
Firmino
